### ISSUE TITLE
Serial Interface on Windows

### ISSUE THREAD

**Issue by ghost** [FIGS-FESS/FESSGUI#33]
Serial object not being created on windows.

**Comment by eric-silk** [comment]
This is just user error on my end. Changing line 15 of flywheeloperation.cpp to "new SerialDevice()" allows me to communicate now.

Still not seeing values being sent down from the GUI, though.

**Comment by ghost** [comment]
The gui currently doesn't send any values to the mcu. I will work on that once I get the settings dialog complete.
